import "server-only";
import { SignJWT, jwtVerify } from "jose";
import { cookies } from "next/headers";

const COOKIE_NAME = "talent_session";
const MAX_AGE_SECONDS = 60 * 60 * 24 * 30; // 30 days
const LINK_MAX_AGE_SECONDS = 60 * 60 * 24 * 7; // 7 days

const secret = process.env.LINE_SESSION_SECRET;
if (!secret) {
  throw new Error("Missing LINE_SESSION_SECRET in .env.local");
}
const encodedSecret = new TextEncoder().encode(secret);

export async function createTalentSession(talentId: string) {
  const token = await new SignJWT({ talentId, purpose: "session" })
    .setProtectedHeader({ alg: "HS256" })
    .setIssuedAt()
    .setExpirationTime(`${MAX_AGE_SECONDS}s`)
    .sign(encodedSecret);

  const cookieStore = await cookies();
  cookieStore.set(COOKIE_NAME, token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax",
    path: "/",
    maxAge: MAX_AGE_SECONDS,
  });
}

// Talent auth mirrors the pattern in lib/supabase/auth-server.ts, but reads
// our own signed cookie instead of a Supabase Auth session — talents never
// touch Supabase Auth.
export async function getTalentSession() {
  const cookieStore = await cookies();
  const token = cookieStore.get(COOKIE_NAME)?.value;
  if (!token) return null;

  try {
    const { payload } = await jwtVerify(token, encodedSecret);
    // "purpose" pins this token to its use: without it, a leaked link
    // token (createTalentLinkToken below) could be dropped straight into
    // the session cookie and used to impersonate that talent without ever
    // proving LINE identity.
    return payload.purpose === "session" && typeof payload.talentId === "string"
      ? { talentId: payload.talentId }
      : null;
  } catch {
    return null;
  }
}

// One-time-ish link generated by an admin for a specific existing talent
// record so a talent who logs in via LINE gets attached to it instead of
// creating a duplicate row. Shared out-of-band (admin sends it over LINE),
// so it's a bearer token — kept short-lived and scoped to "link" purpose
// only (see getTalentSession above).
export async function createTalentLinkToken(talentId: string) {
  return new SignJWT({ talentId, purpose: "link" })
    .setProtectedHeader({ alg: "HS256" })
    .setIssuedAt()
    .setExpirationTime(`${LINK_MAX_AGE_SECONDS}s`)
    .sign(encodedSecret);
}

export async function verifyTalentLinkToken(token: string) {
  try {
    const { payload } = await jwtVerify(token, encodedSecret);
    return payload.purpose === "link" && typeof payload.talentId === "string"
      ? { talentId: payload.talentId }
      : null;
  } catch {
    return null;
  }
}

// Job-offer token: sent to a talent (LINE Flex or copied message) so they
// can open /job/[token] and accept/decline without logging in. Scoped to
// one project_talents row; same purpose-pinning rationale as above.
const JOB_MAX_AGE_SECONDS = 60 * 60 * 24 * 14; // 14 days

export async function createJobToken(projectTalentId: string) {
  return new SignJWT({ projectTalentId, purpose: "job" })
    .setProtectedHeader({ alg: "HS256" })
    .setIssuedAt()
    .setExpirationTime(`${JOB_MAX_AGE_SECONDS}s`)
    .sign(encodedSecret);
}

export async function verifyJobToken(token: string) {
  try {
    const { payload } = await jwtVerify(token, encodedSecret);
    return payload.purpose === "job" && typeof payload.projectTalentId === "string"
      ? { projectTalentId: payload.projectTalentId }
      : null;
  } catch {
    return null;
  }
}
